language: php

php:
  - 5.6
  - 7.0
  - hhvm

addons:
    code_climate:
        repo_token: 3e2d1ea8649d8cecedd51bd72287c5523bd9ed7201b107221f36ceb30faf7714

before_script:
  - composer install --dev --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --verbose --configuration tests/phpunit.xml

after_script:
  - vendor/bin/test-reporter
